name: 'Deploy on YC'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy on cloud'
    runs-on: ubuntu-latest
    env:
      TF_VAR_token: ${{secrets.TF_VAR_TOKEN}}
      TF_VAR_cloud_id: ${{secrets.TF_VAR_CLOUD_ID}}
      TF_VAR_folder_id: ${{secrets.TF_VAR_FOLDER_ID}}
      TF_VAR_zone: ${{secrets.TF_VAR_ZONE}}
      TF_VAR_DOMAIN_ID: ${{secrets.TF_VAR_DOMAIN_ID}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Pull Terraform CLI
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        run: |
          rm -rf ~/.aws
          mkdir -p ~/.aws
          echo '[default]
            aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}' > ~/.aws/credentials
          echo '[default]
            region=ru-central1' > ~/.aws/config
      - name: Run Terraform init
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Run Terraform apply
        run: |
          terraform apply -input=false --auto-approve